# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Base64Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
# python -m PyQt5.uic.pyuic -x Base64Ui.ui -o Base64Ui.py

def base64_decoding(base):
    import base64
    base_decode = base64.b64decode(base)
    url = base_decode.decode('ascii')
    return url

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(600, 450)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")

        self.inputButton = QtWidgets.QPushButton(self.centralwidget)
        self.inputButton.setGeometry(QtCore.QRect(490, 40, 101, 41))
        self.inputButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inputButton.setAutoFillBackground(False)
        self.inputButton.setObjectName("inputButton")

        self.deleteAllButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteAllButton.setGeometry(QtCore.QRect(10, 410, 91, 31))
        self.deleteAllButton.setObjectName("deleteAllButton")

        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(110, 410, 391, 31))
        self.connectButton.setObjectName("connectButton")

        self.deleteSelectButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteSelectButton.setGeometry(QtCore.QRect(510, 410, 80, 31))
        self.deleteSelectButton.setObjectName("deleteSelectButton")

        self.enterAddress = QtWidgets.QLabel(self.centralwidget)
        self.enterAddress.setGeometry(QtCore.QRect(10, 90, 141, 21))
        self.enterAddress.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.enterAddress.setObjectName("enterAddress")

        self.Decoding = QtWidgets.QLabel(self.centralwidget)
        self.Decoding.setGeometry(QtCore.QRect(10, 10, 151, 21))
        self.Decoding.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.Decoding.setObjectName("Decoding")

        self.TextField = QtWidgets.QLineEdit(self.centralwidget)
        self.TextField.setGeometry(QtCore.QRect(10, 40, 471, 40))
        self.TextField.setObjectName("TextField")

        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 120, 580, 281))
        self.listWidget.setObjectName("listWidget")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.inputButton.clicked.connect(self.button_clicked) # type: ignore
        self.deleteAllButton.clicked.connect(self.delete_all_clicked) # type: ignore
        self.connectButton.clicked.connect(self.connect_all_web_clicked) # type: ignore
        self.deleteSelectButton.clicked.connect(self.delete_select_clicked)  # type: ignore

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.inputButton, self.deleteAllButton)
        MainWindow.setTabOrder(self.deleteAllButton, self.connectButton)
        MainWindow.setTabOrder(self.connectButton, self.deleteSelectButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Base64 Decoder"))
        self.inputButton.setText(_translate("MainWindow", "입력"))
        self.deleteAllButton.setText(_translate("MainWindow", "전체 삭제"))
        self.connectButton.setText(_translate("MainWindow", "접속"))
        self.deleteSelectButton.setText(_translate("MainWindow", "삭제"))
        self.enterAddress.setText(_translate("MainWindow", "디코딩"))
        self.Decoding.setText(_translate("MainWindow", "주소 입력"))

    def button_clicked(self):
        print("button_clicked 눌림")
        self.enterAddress.repaint()
        if self.TextField.displayText().find("aHR0c") != -1:
            site = base64_decoding(self.TextField.displayText())
            self.listWidget.addItem(site)

        self.TextField.clear()

    def delete_select_clicked(self):
        print("delete_select_clicked 눌림")
        print(self.listWidget.currentRow())
        self.listWidget.takeItem(self.listWidget.currentRow())

    def delete_all_clicked(self):
        print("delete_all_clicked 눌림")
        self.listWidget.clear()

    def connect_all_web_clicked(self):
        import webbrowser
        print("connect_all_web_clicked 눌림")
        i = 0
        while True:
            if self.listWidget.item(i) is not None:
                print(self.listWidget.item(i).text())
                webbrowser.open_new(self.listWidget.item(i).text())
                i += 1
            else:
                break
        # webbrowser.open(url)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
